### PR TITLE
feat: whether to trigger `this.resize` when window resize

### PR DESCRIPTION
**Pull request by fakership**

### CODE REVIEW

**Comment by fakership** [comment]
echarts will not resize when window resize, so i think the resize shoud not as a default behavoir

**Comment by fakership** [comment]
echarts will not resize when window resize, so i think the resize shoud not as a default behavoir

**Comment by fakership** [comment]
as a config is ok

**Comment by fakership** [comment]
as a config is ok

**Comment by albcunha** [comment]
I came looking for something like this, as when I use react-to-print, echart wont resize.

**Comment by hustcc** [comment]
rename the config to `autoResize`, and default value is `true`.

**Comment by fakership** [comment]
> rename the config to `autoResize`, and default value is `true`.



> rename the config to `autoResize`, and default value is `true`.
done 


> rename the config to `autoResize`, and default value is `true`.

done，i have changed triggerReisize to autoResize

**Comment by nickpresta** [comment]
@hustcc Any chance you can publish this release? It looks like this option isn't available in version `3.0.2`.

Thank you!

**Comment by c3-edwinlo** [comment]
@hustcc +1 to the previous comment, would appreciate if this option was published to release!

**Pull request merged**
