### PR TITLE
 Add typescript declare definition file

### PR DESCRIPTION
**Pull request by echoulen**
Support typescript #97

### CODE REVIEW

**Comment by hustcc** [comment]
@echoulen Thank you very much.

But the commit may contain extra files modify, such as .gitignore, tsc files.

And may be the test case is not in travis.

**Comment by echoulen** [comment]
Dont worry about this,
tsx always compile to __tests__ folder,
You can check travis ci detail like below

**Comment by hustcc** [comment]
But the index.ts.spec.js is in .gitignore?

**Comment by hustcc** [comment]
The declare file seem not very good.

I think it should be coverage index and core. I know little about ts.

**Pull request merged**
