### PR TITLE
deps: upgrade "prop-types" refer to official recommandation

### PR DESCRIPTION
**Pull request by marswong**
in order to avoid unexpected issues.

reference: https://github.com/facebook/prop-types#how-to-depend-on-this-package

### CODE REVIEW

**Comment by marswong** [comment]
yep, actually most of the time it is. just make it meaningful :)

**Comment by hustcc** [comment]
`echarts` should be in devDependence, because demo code use it.

`react-dom` is not necessary for this library, because we did not use any api of it.

**Comment by marswong** [comment]
got it, is that ok now?

**Comment by hustcc** [comment]
props-type should be in dependence.

**Pull request merged**
