### PR TITLE
export echarts from index.js

### PR DESCRIPTION
**Pull request by jbreckel**
as this module needs `echarts` but implementing projects need it too, I think it is nice if this library could export the used version to avoid having to maintain 2 dependencies.

### CODE REVIEW

**Comment by SidKwok** [comment]
I don't think it is a good way to export echarts from echarts-for-react. Users still have to import echarts when they need exact version.

**Comment by jbreckel** [comment]
I know it from [react-apollo](https://github.com/apollographql/react-apollo).

They also export [apollo-client](https://github.com/apollographql/apollo-client) for users to have the same version as they need without having the user to keep the dependencies in sync.

With this change you could `import { echarts } from 'echarts-for-react'` and not have any version collisions.

**Comment by hustcc** [comment]
In this project, we provide 2 way to use echarts:

1. full module import: will import all the scripts of echarts, so the package will be larger
2. just import module as you need in echarts. And developer should put a echarts instance into component props. 

You can get it in README.md file. So, if export echart in this component, problem will occur:

1.  two different usages of two way above.
2. the component need echarts as it's props, also it export the echarts, just a bit strange.

**Comment by jbreckel** [comment]
you currently only allow way 1 as echarts is always imported and bundled.

**Comment by jbreckel** [comment]
yeah this makes sense.

**Pull request closed without merging**
